### ISSUE TITLE
base lower bound is too low for (<>) to be in Prelude

### ISSUE THREAD

**Issue by tomjaguarpaw** [pbrisbin/hs-shellwords#6]
[Hackage claims](https://hackage.haskell.org/package/shellwords) that shellwords supports base >= 4.7 (i.e. back to and including [GHC 7.8.1](https://wiki.haskell.org/Base_package)) but it uses `(<>)` from the `Prelude`. According to [Godbolt](https://godbolt.org/) it wasn't exported from `Prelude` until 8.2 or 8.4.

Perhaps you could fix this issue either by shifting the base dependency to >= 4.12 (8.4) or by explicitly importing `(<>)` from `Data.Monoid`.

**Comment by tomjaguarpaw** [comment]
Oh, based on my passing CI test for [8.2](https://github.com/tomjaguarpaw/haskell-opaleye/actions/runs/2702920911) I know that it was exported in 8.2, so the base dependency of >= 4.10 will be enough.

**Comment by pbrisbin** [comment]
Thanks for reporting! My CI practices on this project must not be up to
date, so this slipped through. I'll get that fixed up today.

**Comment by tomjaguarpaw** [comment]
Thanks! Would you mind doing a dependency revision on the Hackage packages that have this problem? Otherwise I'll keep picking  them up in my CI builds.

**Comment by pbrisbin** [comment]
Yeah, I'll do that once I get `main` sorted and a new version out.

Do you mind listing which `shellwords` version(s) are affecting you?

**Comment by pbrisbin** [comment]
Eh, no worries on that list. I just updated the bound on all released versions. `shellwords-0.1.3.1` is also released with fixed bounds.

**Comment by tomjaguarpaw** [comment]
Thanks! I don't depend on `shellwords` directly. `dotenv` started depending on `shellwords` yesterday, so I picked it up as part of that.

**Comment by tomjaguarpaw** [comment]
(and is why I needed the bounds fixed on all packages, otherwise the cabal resolver would just find one without the bounds revision!)
